#pragma once

// From glfw3.h
#define GAMMAENGINE_MOUSE_BUTTON_1         0
#define GAMMAENGINE_MOUSE_BUTTON_2         1
#define GAMMAENGINE_MOUSE_BUTTON_3         2
#define GAMMAENGINE_MOUSE_BUTTON_4         3
#define GAMMAENGINE_MOUSE_BUTTON_5         4
#define GAMMAENGINE_MOUSE_BUTTON_6         5
#define GAMMAENGINE_MOUSE_BUTTON_7         6
#define GAMMAENGINE_MOUSE_BUTTON_8         7
#define GAMMAENGINE_MOUSE_BUTTON_LAST      GAMMAENGINE_MOUSE_BUTTON_8
#define GAMMAENGINE_MOUSE_BUTTON_LEFT      GAMMAENGINE_MOUSE_BUTTON_1
#define GAMMAENGINE_MOUSE_BUTTON_RIGHT     GAMMAENGINE_MOUSE_BUTTON_2
#define GAMMAENGINE_MOUSE_BUTTON_MIDDLE    GAMMAENGINE_MOUSE_BUTTON_3